// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcGfb3E-r4L0HnY17N9UCej_yRc_HcHno',
    appId: '1:242380418674:web:4ebcc2bb0bd2a859df1ceb',
    messagingSenderId: '242380418674',
    projectId: 'shop-app-dff3e',
    authDomain: 'shop-app-dff3e.firebaseapp.com',
    storageBucket: 'shop-app-dff3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjrwKIqMDSHVsSlh3vDeYNnnM9fPwpuhE',
    appId: '1:242380418674:android:719b5306a4b740b5df1ceb',
    messagingSenderId: '242380418674',
    projectId: 'shop-app-dff3e',
    storageBucket: 'shop-app-dff3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBim2Lz5mNkBqnmI2on_Vre38mt60sbg',
    appId: '1:242380418674:ios:438be8dceaf325b6df1ceb',
    messagingSenderId: '242380418674',
    projectId: 'shop-app-dff3e',
    storageBucket: 'shop-app-dff3e.appspot.com',
    iosClientId: '242380418674-tr46uvrbmjculb6q6plb4bu0mv54u0ks.apps.googleusercontent.com',
    iosBundleId: 'com.mohamedwagdy4153.shopApp',
  );
}
